finger1_joint_controller:
  controller:
    package: softhand_ros
    module: calib_required_joint_position_controller
    type: CalibRequiredJointPositionController
finger2_joint_controller:
  controller:
    package: softhand_ros
    module: calib_required_joint_position_controller
    type: CalibRequiredJointPositionController
finger3_joint_controller:
  controller:
    package: softhand_ros
    module: calib_required_joint_position_controller
    type: CalibRequiredJointPositionController
