finger1_joint_controller:
  controller:
    package: softhand_ros
    module: calib_required_joint_controller
    type: CalibRequiredJointController
  joint_name: finger1_joint_motor
  joint_speed: 5.5
  joint_torque_limit: 0.4
  calib_speed: 1.0
  calib_torque_limit: 0.2
  detect_limit_load: 0.17
  is_multiturn: true
  ignored_errors: ['DXL_OVERLOAD_ERROR']
  motor:
    id: 1
    init: 0
    min: 0
    max: 3500
finger2_joint_controller:
  controller:
    package: softhand_ros
    module: calib_required_joint_controller
    type: CalibRequiredJointController
  joint_name: finger2_joint_motor
  joint_speed: 5.5
  joint_torque_limit: 0.4
  calib_speed: 1.0
  calib_torque_limit: 0.2
  detect_limit_load: 0.17
  is_multiturn: true
  ignored_errors: ['DXL_OVERLOAD_ERROR']
  motor:
    id: 2
    init: 0
    min: 0
    max: 3500
finger3_joint_controller:
  controller:
    package: softhand_ros
    module: calib_required_joint_controller
    type: CalibRequiredJointController
  joint_name: finger3_joint_motor
  joint_speed: 5.5
  joint_torque_limit: 0.4
  calib_speed: 1.0
  calib_torque_limit: 0.2
  detect_limit_load: 0.17
  is_multiturn: true
  ignored_errors: ['DXL_OVERLOAD_ERROR']
  motor:
    id: 3
    init: 3500
    min: 3500
    max: 0
